### ISSUE TITLE
ExecuteIdsQuery returns empty list - deserialization bug?

### ISSUE THREAD

**Issue by sallyShipper** [intuit/QuickBooks-V3-DotNET-SDK#28] opened 2018-03-26 22:11 UTC
Seems similar to issue #23 but with a different call.

**Using ExecuteIdsQuery()**
https://quickbooks.api.intuit.com/v3/company/xxxxxx/query?minorversion=21&requestid=xxxxxx

**Request Body:**
Select * FROM Invoice WHERE MetaData.LastUpdatedTime > '2018-03-24T21:42:59.9658792Z' and MetaData.LastUpdatedTime < '2018-03-26T21:42:59.9147825Z'

**Returns 3 Invoices:**
![image](https://user-images.githubusercontent.com/5014792/37935798-bc23a6a2-3107-11e8-81d5-f36936fc248e.png)

![image](https://user-images.githubusercontent.com/5014792/37935743-8d10b2c4-3107-11e8-9342-123d0e7803eb.png)

However, after deserialization (line 178 in QueryService.cs) - there are no invoices to be found

![image](https://user-images.githubusercontent.com/5014792/37935719-769f7854-3107-11e8-8284-0f695fa23c44.png)

![image](https://user-images.githubusercontent.com/5014792/37935942-5551efd2-3108-11e8-843e-fdfe7ec3d6e1.png)

I have pulled all the latest code from GitHub.  Still not working. 

Thoughts?

**Comment by nbhambhani** [comment] 2018-03-27 22:53
Hi @sallyShipper 
I'm not able to reproduce this. Can you please open a ticket with us [here](https://help.developer.intuit.com/s/contactsupport) and share the OAuth tokens and realm Id so I can try to reproduce it?

**Comment by sallyShipper** [comment] 2018-03-28 19:00
Just did, ticket 00060382. Thx!

**Comment by nbhambhani** [comment] 2018-06-25 17:58
Closing this issue as it is not reproducible even with your QBO tokens.

**Closed by nbhambhani** 2018-06-25 17:58 UTC
