### ISSUE TITLE
Could not load type 'Serilog.ConsoleLoggerConfigurationExtensions' from assembly 'Serilog.Sinks.Debug, Version=2.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10'. 

### ISSUE THREAD

**Issue by rbiq** [intuit/QuickBooks-V3-DotNET-SDK#179] opened 2021-03-18 05:55 UTC
Message: Could not load type 'Serilog.ConsoleLoggerConfigurationExtensions' from assembly 'Serilog.Sinks.Debug, Version=2.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10'. 
 Stack Trace:    at Intuit.Ipp.OAuth2PlatformClient.OAuthAdvancedLogging..ctor(Boolean enableSerilogRequestResponseLoggingForDebug, Boolean enableSerilogRequestResponseLoggingForTrace, Boolean enableSerilogRequestResponseLoggingForConsole, Boolean enableSerilogRequestResponseLoggingForFile, String serviceRequestLoggingLocationForFile)
   at Intuit.Ipp.OAuth2PlatformClient.OAuth2Client.GetAuthorizationURL(List`1 scopes) in C:\Users\rkasaraneni\QuickBooks-V3-DotNET-SDK\IPPDotNetDevKitCSV3\Code\Intuit.Ipp.OAuth2PlatformClient\Client\OAuth2Client.cs:line 322

Downloaded latest qbo .net sdk from nuget and started receiving this error. Please suggest a solution or fix urgently as this has stopped working for us and we're in the process of deploying to production.

**Comment by Megaventory** [comment] 2021-03-18 07:01
This is a duplicate of #176 which the owners of the repo have now closed (without specific reasoning). You can either downgrade to the previous version of  Serilog.Sinks.Debug or fork the repo and build locally removing all serilog references from projects and code. I chose the 2nd method.

**Comment by nimisha84** [comment] 2021-03-18 21:24
This is a dll hell issue. Please delete your bin folder , unistall package and then clean project and install again and build. That should resolve this issue. @Megaventory that issue was closed as we thought the issue was resolved after discussion with @mlenow. Can you also try resolving the dll hell and see if that fixes the issue for you. What dotnet framework version are you on?

**Comment by Megaventory** [comment] 2021-03-20 09:16
@nimisha84 , I do not believe this is a DLL hell issue. The SDK is not well maintained. Let's be honest. There are nuget packages that are referenced by this SDK (serilog) which have a security warning and which no uninstall or upgrade is possible because this SDK depends on the deprecated versions. At the very least, you can ensure the SDK does not depend on packages that are not secure but also that it depends on the latest package versions. I had to fork the repo and build locally removing all serilog packages and their references in the code just to be safe.

**Comment by nimisha84** [comment] 2021-03-20 22:47
Please share a screenshot of the warning. Also, thanks for the feedback. We do updates on this SDK every quarter and yes it is not frequent intentionally as these SDKs are in maintenance mode but we do make sure to upgrade packages every qtrly release. There are also other reason why some of the packages are not latest as this SDK is on .net Standard and for it to support .Net Framework 4.6.0, 4.7.2 we need to some old versions of some of the packages.

**Comment by Megaventory** [comment] 2021-03-21 09:02
@nimisha84 see https://github.com/intuit/QuickBooks-V3-DotNET-SDK/issues/156

**Closed** 2021-04-09 16:58 UTC
